name: Build Windows Exe, Installer and Extension
run-name: ${{ github.actor }} Started a Build
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pywin32
          pip install flask
          pip install pillow
          pip install tkinter
      - name: Build Windows .exe
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "entelock.ico" --name "Ente Auth Tray"  "ente-tray.py"
          rmdir build
          rm .'\Ente Auth Tray.spec'
      - name: Build Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: winstaller.iss
      - name: Zip Browser Extension
        run: |
          Compress-Archive -Path extension -DestinationPath ente_auth_ext.zip
      - name: Upload Everything
        uses: actions/upload-artifact@v4
        with:
          name: EnteAuthBuilds
          path: |
            dist\Ente Auth Tray.exe
            dist\EnteAuthTrayInstaller.exe
            ente_auth_ext.zip